**What is Numpy?**
NumPy (short for "Numerical Python") is a Python library that supports large, multi-dimensional arrays. It also comes with a bunch of math functions that you can use to operate on these arrays.

Installing NumPy in Python

In [ ]:
!pip install numpy

Once installed, import the library with the alias np

In [ ]:
import numpy as np

Checking NumPy Version

In [ ]:
print(np.__version__)

2.0.2


# Creating NumPy Arrays

NumPy arrays are created using the array() function. An array is the core data structure of the NumPy package. It’s a grid of values.

Here’s what a Python list looks like:

rent = [1500, 1500, 1500, 1500, 1750, 1750]

And here’s an example of a NumPy array:

In [ ]:
rent = np.array([1500, 1500, 1500, 1500, 1750, 1750])

print(rent)

[1500 1500 1500 1500 1750 1750]


We initialized it from a Python list. Since we nicknamed numpy as np, it’s np.array() with the Python list inside.

In [ ]:
twoD = np.array([[1, 2, 3], [4, 5, 6]])

print(twoD)

[[1 2 3]
 [4 5 6]]


In [ ]:
threeD = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(threeD)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
d = np.array([[0, 0, 0],[0, 0, 0],[0, 0, 0]])
print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
e = np.zeros((1,3))
print(e)

[[0. 0. 0.]]


In [ ]:
a = np.zeros((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b = np.ones((2, 2))
print(b)


[[1. 1.]
 [1. 1.]]


In [ ]:
cc = np.array([0,2,4,6,8,10])
print(cc)

[ 0  2  4  6  8 10]


In [ ]:
c = np.arange(500, 600, 18)
print(c)

[500 518 536 554 572 590]


# NumPy Array Indexing
In Python lists, we access individual items using the bracket notation. In NumPy arrays, we can access individual arrays the same way!

The following array contains the coffee intake in a work week. ☕️

coffee = np.array([3, 2, 1, 0, 1])

The element at index 0 is 3.
The element at index 1 is 2.
The element at index 2 is 1.
The element at index 3 is 0.
The element at index 4 is 1.

In [ ]:
coffee = np.array([3, 2, 1, 0, 1])
print(coffee[4])

1


In [ ]:
chai = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', chai[1, 0])

2nd element on 1st row:  6


**Slicing**
Slicing is where we can access certain parts of a sequence. We can get multiple elements by specifying where to start slicing and where to end like name[start : end]. We can also define the step, like this: [start:end:step]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
#elements from index 1 to 3
print("Range of Elements:",arr[1:4])

#all rows, second column
print("Multidimensional Slicing:", arr[:, 1])

Range of Elements: [[4 5 6]]
Multidimensional Slicing: [2 5]


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

print(arr[2:7:2])

[2 4 6]


# NumPy Data Types


In [ ]:
arr_data = np.array([1, 2, 3, 4])

print(arr_data.dtype)

float64


# NumPy Array Shape

In [ ]:
print(arr_data.shape)

(4,)


# NumPy Array Reshaping

In [ ]:
arr_reshape = arr_data.reshape(2, 2) #(row, column)

print(arr_reshape)

[[1 2]
 [3 4]]


# NumPy Joining Array

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
add = arr1 + arr2
print(arr)
print(add)

[1 2 3 4 5 6]
[5 7 9]


# NumPy Splitting Array

In [ ]:
arr_split = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr_split, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# NumPy Searching Arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 4, 4])

z = np.where(a == 4)

print(z)

(array([3, 5, 6]),)


In [ ]:
g = np.array([1, 3, 5, 7, 9])

q = np.searchsorted(g, [2, 6, 8])

print(q)

[1 3 4]


# NumPy Sorting Arrays

In [ ]:
print(np.sort(z))

In [ ]:
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))

print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


# NumPy Basic Operations

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
add = x + y
print("Addition:",add)

# Subtraction
subtract = x - y
print("substration:",subtract)

# Multiplication
multiply = x * y
print("multiplication:",multiply)

# Division
divide = x / y
print("division:", divide)

Addition: [5 7 9]
substration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


In [ ]:
abs = np.array([-3, -1, 0, 1, 3])

# Applying a unary operation: absolute value
result = np.absolute(abs)
print("Absolute value:", result)

Absolute value: [3 1 0 1 3]


In [ ]:
sin_a = np.array([0, np.pi/2, np.pi])
print ("Sine values:", np.sin(sin_a))

# exponential values
print ("Exponent of array elements:", np.exp(x))

# square root of array values
print ("Square root of array elements:", np.sqrt(y))

Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 2.71828183  7.3890561  20.08553692]
Square root of array elements: [2.         2.23606798 2.44948974]
